# Generated by Django 4.0.3 on 2022-04-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similar_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar', models.FloatField(default=0)),
                ('movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie1', to='polls.movie')),
                ('movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie2', to='polls.movie')),
            ],
        ),
    ]
